---
title: "Homework 5"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
Loading of necessary libraries.
```{r, message=FALSE, warning=FALSE, error=FALSE}
library(tidyverse)
library(rmarkdown)
library(lubridate)
library(tigris)
library(sf)
library(tidyverse)
library(forcats)
options(tigris_class = "sf")
options(tigris_use_cache = TRUE)
```
Loading and cleaning of data. 
```{r, message=FALSE, warning=FALSE, error=FALSE}
homicides <- read_csv("../data/homicide_data.csv") %>% 
  unite(col = "city_state", city, state, sep = ",") %>% 
  mutate(reported_date = ymd(reported_date),
         victim_first = str_to_sentence(victim_first),
         victim_last = str_to_sentence(victim_last),
         disposition = str_to_lower(disposition),
         disposition = str_replace(disposition, "closed without arrest", "no arrest"),
         disposition = str_replace(disposition, "open/no arrest", "no arrest")) %>% 
  filter(city_state == "Chicago,IL") %>% 
  print()
```
Creation of map of Chicago,IL.  
Concersion of df to sf object of homicides.
Thanks Kyle! https://walkerke.github.io/2017/05/tigris-metros/  
```{r, message=FALSE, warning=FALSE, error=FALSE, fig.width=8, fig.height=8}
homicides$victim_race <- as.factor(homicides$victim_race) 

sf_homicides <- st_as_sf(x = homicides, coords = c("lon", "lat")) %>% 
  st_set_crs(4269) 

chicago <- tracts("IL", county = "Cook", cb = TRUE)

ggplot() +
  geom_sf(data = chicago) +
  geom_sf(data = sf_homicides, alpha = 0.4, 
          aes(color = fct_lump(victim_race, n = 3))) +
  facet_wrap("disposition", strip.position = c("bottom")) +
  scale_color_viridis_d() +
  ggtitle("Chicago Homicide incidents from 2007-2009", subtitle = "Murders separated by successful arrest or not") +
  theme_void() +
  theme(panel.background = element_rect(fill = "black"),
        plot.background = element_rect(fill = 'grey'),
        legend.title=element_blank()) 
```

